---
title: "silge_text_classification"
author: "Sefa Ozalp"
date: "2020-02-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
# https://www.r-bloggers.com/text-classification-with-tidy-data-principles/

library(tidyverse)
library(gutenbergr)
library(tidytext)
```

## Import two books
```{r}
titles <- c(
  "The War of the Worlds",
  "Pride and Prejudice"
)

books <- gutenberg_works(title %in% titles) %>%
  gutenberg_download(meta_fields = "title") %>%
  mutate(document = row_number())

books %>% 
  rmarkdown::paged_table()

books %>% 
  count(title)
```


```{r}
books_tidy <- books %>% 
  unnest_tokens(word, text, token = "words") %>% 
  group_by(word) %>%
  # filter(n() > 10) %>% 
  ungroup()
```


Chart of most freq words
```{r}
books_tidy %>% 
  count(title, word, sort = T) %>% 
  anti_join(get_stopwords()) %>%
  group_by(title) %>% 
  top_n(20) %>% 
  ungroup() %>% 
  ggplot(aes(reorder_within( word, n, title),n, fill=title))+
  geom_col(show.legend = F)+
  coord_flip()+
  scale_x_reordered() + # this is from tidytext and a bit hacky
  facet_wrap(~title, scales = "free")+
  scale_y_continuous(expand = c(0, 0)) +
  labs(
    x = NULL, y = "Word count",
    title = "Most frequent words after removing stop words",
    subtitle = "Words like 'said' occupy similar ranks but other words are quite different"
  )
  NULL
  

```


## Building a ML model

```{r}
library(rsample)
books_split <- books %>%
  select(document) %>%
  initial_split()
train_data <- training(books_split)
test_data <- testing(books_split)

# create a sparse amtrix
sparse_words <- books_tidy %>%
  count(document, word) %>%
  inner_join(train_data) %>% # this act as a filter here 
  cast_sparse(document, word, n)

class(sparse_words)
dim(sparse_words)



word_rownames <- as.integer(rownames(sparse_words)) 

books_joined <- tibble(document = word_rownames) %>%
  left_join(books %>%
    select(document, title))# dataframe with response variable


```


```{r}

library(glmnet)
library(doMC)
registerDoMC(cores = 4)
```

```{r}
is_jane <- books_joined$title == "Pride and Prejudice"
model <- cv.glmnet(sparse_words, is_jane,
  family = "binomial",
  parallel = TRUE, keep = TRUE
)
```

```{r}
plot(model)

plot(model$glmnet.fit)

```

## Understanding the model
```{r}
library(broom)

coefs <- model$glmnet.fit %>%
  tidy() %>%
  filter(lambda == model$lambda.1se)

coefs %>%
  group_by(estimate > 0) %>%
  top_n(10, abs(estimate)) %>%
  ungroup() %>%
  ggplot(aes(fct_reorder(term, estimate), estimate, fill = estimate > 0)) +
  geom_col(alpha = 0.8, show.legend = FALSE) +
  coord_flip() +
  labs(
    x = NULL,
    title = "Coefficients that increase/decrease probability the most",
    subtitle = "A document mentioning Martians is unlikely to be written by Jane Austen"
  )
```

## Evaluate the model
```{r}
intercept <- coefs %>%
  filter(term == "(Intercept)") %>%
  pull(estimate)

classifications <- books_tidy %>%
  inner_join(test_data) %>%
  inner_join(coefs, by = c("word" = "term")) %>%
  group_by(document) %>%
  summarize(score = sum(estimate)) %>%
  mutate(probability = plogis(intercept + score))

classifications
```

## Model performance metrics
```{r}
library(yardstick)

comment_classes <- classifications %>%
  left_join(books %>%
    select(title, document), by = "document") %>%
  mutate(title = as.factor(title))

comment_classes %>%
  roc_curve(title, probability) %>%
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_line(
    color = "midnightblue",
    size = 1.5
  ) +
  geom_abline(
    lty = 2, alpha = 0.5,
    color = "gray50",
    size = 1.2
  ) +
  labs(
    title = "ROC curve for text classification using regularized regression",
    subtitle = "Predicting whether text was written by Jane Austen or H.G. Wells"
  )


```

```{r}
comment_classes %>%
  roc_auc(title, probability)
```

```{r}
comment_classes %>%
  mutate(
    prediction = case_when(
      probability > 0.5 ~ "Pride and Prejudice",
      TRUE ~ "The War of the Worlds"
    ),
    prediction = as.factor(prediction)
  ) %>%
  conf_mat(title, prediction)


```
## Understand misclassifications

### Mis-classified as written by Jane Austen
```{r}
comment_classes %>%
  filter(
    probability > .8,
    title == "The War of the Worlds"
  ) %>%
  sample_n(10) %>%
  inner_join(books %>%
    select(document, text)) %>%
  select(probability, text)
```

### Misclassified as not written by Jane 
```{r}
comment_classes %>%
  filter(
    probability < .3,
    title == "Pride and Prejudice"
  ) %>%
  sample_n(10) %>%
  inner_join(books %>%
    select(document, text)) %>%
  select(probability, text)
```

